### ISSUE TITLE
Human Readable Overlay Names

### ISSUE THREAD

**Issue by RobLoach** [libretro/common-overlays#68]
Right now, when you load up the Overlay Presets, you're presented with a directory structure of overlay directories and files. While it is workable, it would be nice if we applied some clean up of the names to make them a bit more readable for the end user.

![Screenshot at 2021-10-16 05-00-36](https://user-images.githubusercontent.com/25086/137581507-e1e832d8-4d3e-4769-8267-72a3fce9c753.png)

Rather than having them just be under-cased directories and file names, I'm proposing renaming these a bit to seem a bit more human readable, not only for the parent folder, but also all children files/folders...

![Screenshot at 2021-10-16 05-04-09](https://user-images.githubusercontent.com/25086/137581621-77acfafe-b07a-4f53-8dbf-dcf40681ea55.png)

**Comment by hizzlekizzle** [comment]
That seems good to me. I'm down for renames, too. E.g., should CTR be changed to 3DS?

**Comment by RobLoach** [comment]
Update on this one... RetroArch has hardcoded the overlay paths, so we won't be able to tak ethis one on.
